apps/sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.search, name='search'),
    path('orders_report/', views.orders_report, name='orders_report'),
    path('order_create/<slug:slug>', views.order_create, name='order_create')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler403, handler404, handler500

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('apps.account.urls')),
    path('', include('apps.sales.urls', namespace='sales')),
    path('quest/', include('apps.content.urls', namespace='content')),
    path('', include('social_django.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler400 = 'apps.sales.views.page_not_found'
handler403 = 'apps.sales.views.page_not_found'
handler404 = 'apps.sales.views.page_not_found'
handler500 = 'apps.sales.views.page_not_found_500'

apps/sales/models.py
from decimal import Decimal
from django.contrib.auth.base_user import BaseUserManager
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from ..account.models import User
from ..content.models import Quest


class Order(models.Model):
    """ Модель для заказов пользователя"""
    client = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE,
                               verbose_name='Заказ Пользователя')
    manager = models.ForeignKey("Manager", related_name='orders_manager', on_delete=models.CASCADE,
                                verbose_name='Менеджер')
    comment = models.CharField('Комментарий к заказу', max_length=100)
    is_confirmed = models.BooleanField('Подвержден?', default=False)
    date_creation = models.DateTimeField(verbose_name='Дата создания заказа', auto_now_add=True)
    time_start = models.DateTimeField(verbose_name='Дата\Время старта')
    time_finish = models.DateTimeField(verbose_name='Дата\Время окончания')
    status = models.ForeignKey("Status",
                               related_name='status',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL, verbose_name='Статус')
    coupon = models.ForeignKey("Coupon",
                               related_name='coupons',
                               null=True,
                               blank=True,
                               on_delete=models.SET_NULL, verbose_name='Купон')
    quest = models.ForeignKey(Quest,
                              related_name='quest',
                              null=True,
                              blank=True,
                              on_delete=models.SET_NULL, verbose_name='Квест')
    count_players = models.PositiveIntegerField(default=2,
                                                validators=[MinValueValidator(1), MaxValueValidator(5)],
                                                verbose_name='Количество игроков')
    objects = BaseUserManager()

    class Meta:
        ordering = ('id',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return "Заказ № {}".format(self.id)

    def get_order_quests(self):
        quests = Quest.objects.filter(order=self)
        return quests

    def get_discount(self) -> int:
        if self.coupon:
            discount = self.coupon.discount
        else:
            discount = 0
        return discount

    def get_discount_percent(self):
        return "{} %".format(self.get_discount())

    get_discount_percent.short_description = 'Скидка'

    def get_total_cost(self):
        return self.quest.price

    get_total_cost.short_description = 'Стоимость заказа'

    def get_total_cost_discount(self):
        total_cost = self.quest.price
        if self.get_discount() == 0:
            return total_cost
        else:
            return total_cost - total_cost * (self.get_discount() / Decimal('100'))

    get_total_cost_discount.short_description = 'Стоимость заказа со скидкой'


class Coupon(models.Model):
    name = models.CharField(max_length=50, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField()
    objects = BaseUserManager()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Купон'
        verbose_name_plural = 'Купоны'

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование статуса')
    description = models.CharField(max_length=150, verbose_name='Описание статуса', blank=True)
    objects = BaseUserManager()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return self.name


class Manager(models.Model):
    POST_CHOISES = (
        ('Менеджер', 'Менеджер'),
        ('Старший менеджер', 'Старший менеджер'),
        ('Администратор', 'Администратор'),
    )
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE,
                             verbose_name='Пользователь')
    post = models.CharField(choices=POST_CHOISES, verbose_name="Должность", max_length=60)
    objects = BaseUserManager()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

    class Meta:
        ordering = ('post',)
        verbose_name = 'Менеджер'
        verbose_name_plural = 'Менеджеры'

    def get_all_sales(self):
        """ все продажи менеджера за всё время"""
        return Order.objects.filter(manager=self)

apps/sales/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic.list import ListView

from .models import *
from django.db.models import Q
from ..content.models import Quest


class IndexView(ListView):
    """ Вью для главной страницы, все квесты"""
    queryset = Quest.objects.all()
    template_name = 'sales/index.html'
    context_object_name = 'quests'
    paginate_by = 6


def page_not_found(request, exception):
    template = 'core/404.html'
    status = 404
    context = locals()
    return render(request, template, context)


def page_not_found_500(request):
    template = 'core/500.html'
    status = 500
    context = locals()
    return render(request, template, context)


def search(request):
    """ функция поиска """
    query = request.GET.get('q')
    # изменяем регистр первого символа запроса. проанализировать надо будет
    query = query.title()
    quests = Quest.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'sales/search.html', {'quests': quests,
                                                 'query': query})


def get_orders_total_count():
    """ функция, рассчитывающая итоговое количество заказов за весь период"""
    return Order.objects.all().count()


def get_total_sum_all_orders():
    """ функция, рассчитывающая итоговую сумму по всем заказам со скидкой"""
    total_sum = sum(order.get_total_cost_discount() for order in Order.objects.all())
    return total_sum


def orders_report(request):
    """ Отчет по продажам"""
    managers = Manager.objects.all()
    orders_total_count = get_orders_total_count()
    total_sum_all_orders = get_total_sum_all_orders()
    context = locals()
    return render(request, 'sales/orders_report.html', context)


def order_create(request, slug):
    """ Заглушка на форму заказа квеста"""
    quest = Quest.objects.get(slug=slug)
    if request.user.is_authenticated:
        Order.objects.create(quest=quest,
                             client=request.user,
                             time_start="2021-12-09 14:00:00",
                             time_finish="2021-12-09 15:00:00",
                             status=Status.objects.get(name='Новый'),
                             manager=Manager.objects.get(id=1)
                             )
        messages.success(request, "Вы успешно заказали квест!")
        return redirect('content:quest_detail', quest.slug)
    else:
        messages.error(request, "Для заказа квеста авторизуйтесь на сайте")
        return redirect('login')

apps/templates/sales/base.html
{% load static %}
{% autoescape off %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="ru">
<link rel="icon" href="https://faviconka.ru/ico/1/faviconka.ru_1_16865.ico" type="image/x-icon" />
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--    Подключаем css-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<!--    Подключаем jquery-->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="main">
    <header>
        <div class="logo">
            <a href="/">
                <img src="{% static 'img/quest_logo.png' %}"></a><br>
        </div>

        <div class="search">
           <form action="{% url 'sales:search' %}" method="get">
               <input name="q" type="text" placeholder="Поиск.." >
           </form>
        </div>

        <div class="main_tabs">
                <a href="{% url 'sales:index' %}">Все квесты</a>
                <a href=".">Условия</a>
                <a href=".">Рейтинг</a>
                <a href=".">FAQ</a>

                {% if request.user.is_staff %}
                    <a href="{% url 'sales:orders_report' %}">Отчет по заказам</a>
                    <a href="{% url 'admin:index' %}">CRM</a>
                {% endif %}
        </div>

        <div class="head_login">
            {% if request.user.is_authenticated %}
              <a href="{% url 'profile' %}">Личный кабинет</a>
            {% else %}
              <a href="{% url 'login' %}">Вход на сайт</a>
            {% endif %}
        </div>
    </header>

        <div class="content">
           <div class="block_messages">
                {% if messages %}
                  <ul class="messages">
                   {% for message in messages %}
                    <li class="{{ message.tags }}">
                      {{ message|safe }}
                        <a href="." class="close">x</a>
                    </li>
                  </ul>
                   {% endfor %}
                {% endif %}
           </div>
            {% block content %}
            {% endblock %}
        </div>
 </div>
        <footer>
            <div class="channels">
                <p class="grey">Наши каналы:</p>
                <div class="channels-logo">
                    <div>
                        <a href="/">
                        <img src="{% static 'img/yandex.png' %}"></a><br>
                    </div>
                    <div class="telegram">
                        <a href="/">
                        <img src="{% static 'img/telegram.png' %}"></a><br>
                    </div>
                </div>
            </div>
        </footer>

</body>
</html>
{% endautoescape %}

apps/templates/sales/index.html
{% extends "sales/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}Лучшие квесты в твоём городе{% endblock %}

{% block content %}
        {% for quest in quests %}
            <div class="post">
                <b><a href="{{ quest.get_absolute_url }}">{{ quest.name }}<br>
                    <img src="{% thumbnail quest.image 300x300 crop %}"></a></b><br>
                    Цена {{ quest.price }} р.<br>
                    Длительность {{ quest.duration }}<br>
                <button><a href="{% url 'sales:order_create' quest.slug %}">Забронировать</a></button>

            </div>
         {% endfor %}
{% endblock %}

apps/templates/sales/orders_report.html
{% extends "sales/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} Отчет по продажам{% endblock %}

{% block content %}
    <p><a href="{% url 'sales:index' %}">Главное меню</a> / Отчет по заказам</p>

    <p>Отчет по заказам:</p>
    {% if managers %}
        {% for manager in managers %}
            {{ manager }}    "{{ manager.post }}"
    <table id="table_orders_report">
         <tr>
            <th>Номер заказа</th>
            <th>Статус заказа</th>
            <th>Стоимость заказа</th>
        </tr>
        {% for order in manager.get_all_sales %}
            <tr>
                <td>
                     {{ order.id }}
                </td>
                 <td>
                     {{ order.status.name }}
                </td>
                <td>
                     {{ order.get_total_cost_discount }}
                </td>
            </tr>
        {% endfor %}
        </table> <br>
       {% endfor %}
       <div class="total_completed_orders">
            Итого заказов: <b>{{ orders_total_count }}</b> на сумму <b>{{ total_sum_all_orders }} р.</b>
        </div>
    {% endif %}
{% endblock %}

apps/templates/sales/search.html
{% extends "sales/base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %} Топ 10 коллекций {% endblock %}

{% block content %}
    <p><a href="{% url 'sales:index' %}">Главное меню</a> / Результаты поиска</p>
    {% if quests %}
        {% for quest in quests %}
            <div class="post">
                <b><a style="color:black" href="{{ quest.get_absolute_url }}">{{ quest.name }}
                    <img src="{% thumbnail quest.image 300x300 crop %}"></a></b>  <br>
            </div>
        {% endfor %}
    {% else %}
        <p>По запросу <b>{{ query }}</b> ничего не найдено. Попробуйте еще</p>
    {% endif %}
{% endblock %}